export enum ROUTE {
  'LOGIN' = '/login',
  'FORGOT_PASSWORD' = '/forgot',
  'REGISTER' = '/register',
  'SHOP' = '/shop',
  'WISHLIST' = '/wishlist',
  'CHECKOUT' = '/checkout',
  'LAPTOP' = '/laptop',
  'CLOTHES' = '/clothes',
  'BOOK' = '/book',
  'DASHBOARD_eCOMMERCE' = '/dashboard/e-commerce',
  'DASHBOARD_ANALYTICS' = '/dashboard/analytics',
  'HOME' = '/',
  'NOT_FOUND' = '*',
}
